removing unused ignore type comment
src/cloudformation_cli_python_lib/recast.py:130: error: unused 'type: ignore' comment
https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/pull/145/checks?check_run_id=1513282646